# Site settings
baseURL = "https://blog.gangelov.net/"
languageCode = "bg-bg"
title = "Просто един блог"

theme = "cactus-plus"

googleAnalytics = "UA-18376726-1"

# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages)
# characters
hasCJKLanguage = false

[params]
	author = "Георги Ангелов"
	description = "Просто един блог за разни програмистки неща"

	bio = "The steps you take don't have to be big, they just need to take you in the right direction."

	twitter = "stormbreakerbg"
	facebook = "stormbreakerbg"

	enableRSS = true
	enableToc = false

	# enableDisqus = true
	# disqusShortname = "your_disqus_short_name"

	enableSummary = true

	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = true

	enableGoogleAnalytics = true

	# enableTwitterCard = true

	# The url for twitter card image, default is avatar.png in static/images directory
	# twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = ['css/custom.css']
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = "Начало"
	about = "За мен"
	archive = "Архиви"
	subscribe = "RSS"

	olderPosts = "По-стари постове"
	newerPosts = "По-нови постове"
	# copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = "Прочети още"

	# Share
	enableShare = false
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"

    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = ""


# Add additional social link entries underneath
[social]
	# facebook-square = "https://www.facebook.com/nodejh"
	# twitter-square = "https://www.twitter.com/nodejh"
	# github-square = "https://www.github.com/nodejh"

[markup]
	[markup.highlight]
		style = "github"
